name: remindme
description: First Flutter Project, to remind you about things you already did.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.9

  provider: ^6.0.0
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.9.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true